"""Credit terms used in the report: the banker's term, what it stands for, a
plain-English meaning and how this report computes it. One source for labels,
hover text and the glossary section, so wording stays consistent."""

TERMS = {
    "ltm": ("LTM", "Last twelve months (TTM)", "The 12 months up to the extraction date.",
            "Rolling 365-day window ending on the report date."),
    "yoy": ("YoY growth", "Year-on-year growth", "How much sales grew compared with the same period a year earlier.",
            "(LTM sales − prior 12-month sales) ÷ prior 12-month sales."),
    "gross_margin": ("Gross margin", "Gross profit margin", "What is left from each ₹100 of sales after the cost of goods.",
                     "(Sales + direct income − COGS) ÷ sales."),
    "cogs": ("COGS", "Cost of goods sold", "What the goods that were sold cost the company.",
             "Purchases + direct expenses − (closing stock − opening stock)."),
    "net_margin": ("Net margin", "Net profit margin (pre-tax, as booked)", "Profit left from each ₹100 of sales after all expenses.",
                   "Net profit ÷ sales, from voucher-level P&L."),
    "ebitda": ("EBITDA", "Earnings before interest, tax, depreciation and amortisation",
               "Operating profit: the cash-like profit the business earns before financing costs.",
               "Net profit + interest + depreciation (identified by ledger name)."),
    "hhi": ("HHI", "Herfindahl-Hirschman Index", "How concentrated sales are among customers (0 = spread out, 10,000 = one customer).",
            "Sum of squared % shares of each customer. < 1,500 unconcentrated; 1,500-2,500 moderate; > 2,500 high."),
    "top1": ("Top-1 share", "Largest-customer concentration", "Share of sales from the single largest customer.",
             "Largest customer's LTM sales ÷ total LTM credit-customer sales."),
    "top5": ("Top-5 share", "Top-5 customer concentration", "Share of sales from the five largest customers.",
             "Top 5 customers' LTM sales ÷ total LTM credit-customer sales."),
    "nrr": ("NRR", "Net revenue retention", "How much repeat customers bought this year vs last year.",
            "LTM sales to customers active in both periods ÷ their prior-year sales."),
    "dso": ("DSO", "Days sales outstanding", "Debtor days: average number of days customers take to pay.",
            "Trade receivables ÷ LTM credit sales (incl. GST) × 365."),
    "dpo": ("DPO", "Days payables outstanding", "Creditor days: average number of days the company takes to pay suppliers.",
            "Trade payables ÷ LTM credit purchases (incl. GST) × 365."),
    "dio": ("DIO", "Days inventory outstanding", "Inventory days: how many days of stock the company holds.",
            "Closing stock ÷ LTM COGS × 365."),
    "ccc": ("CCC", "Cash conversion cycle (cash-to-cash cycle)",
            "Days between paying suppliers and collecting from customers: the gap the bank's working-capital limit funds.",
            "DSO + DIO − DPO."),
    "ageing": ("Ageing", "Receivables / payables ageing", "How old the unpaid bills are.",
               "Outstanding split by bill date: bill-wise where Tally tracks bills, else FIFO against invoices."),
    "recv_90": ("Receivables > 90 days", "Overdue ageing bucket", "Share of money owed by customers that is more than 3 months old.",
                "(91-180 + 181-365 + > 365-day buckets) ÷ total receivables."),
    "collection_ratio": ("Collection efficiency", "Collections ÷ billing",
                         "How much of what was billed to customers was actually collected.",
                         "LTM receipts from customers ÷ LTM credit billing."),
    "current_ratio": ("Current ratio", "Current assets ÷ current liabilities",
                      "Can short-term assets pay the bills due within a year? Banks typically look for 1.33× or more.",
                      "(Cash, bank, debtors, stock, advances) ÷ (creditors, taxes, provisions, OD/CC)."),
    "quick_ratio": ("Quick ratio", "Acid-test ratio", "Current ratio without stock: can it pay without selling inventory?",
                    "(Current assets − stock) ÷ current liabilities."),
    "tnw": ("TNW", "Tangible net worth", "The owners' own money in the business, excluding intangible items.",
            "Total assets − outside liabilities − misc. expenses (asset)."),
    "debt_tnw": ("Debt / TNW", "Gearing (debt-to-equity)", "Borrowings for every ₹1 of the owners' own money.",
                 "(Secured + unsecured loans + OD/CC) ÷ TNW."),
    "tol_tnw": ("TOL / TNW", "Total outside liabilities to tangible net worth",
                "Everything owed to outsiders for every ₹1 of the owners' money. Banks commonly cap this around 3-4×.",
                "(Loans + current liabilities) ÷ TNW."),
    "icr": ("ICR", "Interest coverage ratio", "How many times operating profit covers the interest bill.",
            "EBITDA ÷ interest expense."),
    "dscr": ("DSCR", "Debt service coverage ratio (approx.)",
             "How many times operating profit covers interest plus loan instalments. Below 1.2× is usually a concern.",
             "EBITDA ÷ (interest + principal repaid on term and unsecured loans, LTM)."),
    "od_cc": ("OD / CC", "Overdraft / cash credit", "The working-capital limit drawn from the bank.",
              "Credit balances in Bank OD / OCC ledgers and overdrawn current accounts."),
    "cash_receipts": ("Cash receipts share", "Cash share of customer collections",
                      "Share of customer payments received in cash instead of through the bank.",
                      "LTM cash receipts from debtors ÷ all receipts from debtors."),
    "cv": ("CV", "Coefficient of variation (seasonality)", "How much monthly sales swing up and down.",
           "Standard deviation of monthly LTM sales ÷ their mean."),
    "window_dressing": ("Window dressing", "Year-end sales inflation", "Sales booked at year end that are reversed afterwards.",
                        "March sales > 1.6× the year's average month; April credit notes > 10% of March sales."),
    "circular": ("Circular trading", "Round-tripping between related parties",
                 "The same party buying and selling with the company, which can inflate turnover.",
                 "Debtor and creditor ledgers matched by GSTIN or normalised name."),
    "backdating": ("Back-dated entries", "Entries out of creation order", "Vouchers keyed in later but dated earlier.",
                   "Vouchers whose MasterID (creation order) is after vouchers dated 30+ days later."),
    "269st": ("s.269ST", "Income Tax Act s.269ST", "Law barring receipt of ₹2 lakh or more in cash in a transaction.", ""),
    "40a3": ("s.40A(3)", "Income Tax Act s.40A(3)", "Cash expenses above ₹10,000 are not tax-deductible.", ""),
}


def term(key: str) -> dict:
    abbr, name, plain, formula = TERMS[key]
    return {"key": key, "abbr": abbr, "name": name, "plain": plain, "formula": formula}


def all_terms() -> list[dict]:
    return sorted((term(k) for k in TERMS), key=lambda t: t["abbr"].lower())
