"""Credit terms used in the report: the banker's term, what it stands for, a
plain-English meaning and how this report computes it. One source for labels,
hover text and the glossary section, so wording stays consistent."""

TERMS = {
    "ltm": ("LTM", "Last twelve months (TTM)", "The 12 months up to the extraction date.",
            "Rolling 365-day window ending on the report date."),
    "yoy": ("YoY growth", "Year-on-year growth", "How much sales grew compared with the same period a year earlier.",
            "(LTM sales − prior 12-month sales) ÷ prior 12-month sales."),
    "gross_margin": ("Gross margin", "Gross profit margin", "What is left from each ₹100 of sales after the cost of goods.",
                     "(Sales + direct income − COGS) ÷ sales."),
    "cogs": ("COGS", "Cost of goods sold", "What the goods that were sold cost the company.",
             "Purchases + direct expenses − (closing stock − opening stock)."),
    "net_margin": ("Net margin", "Net profit margin (pre-tax, as booked)", "Profit left from each ₹100 of sales after all expenses.",
                   "Net profit ÷ sales, from voucher-level P&L."),
    "ebitda": ("EBITDA", "Earnings before interest, tax, depreciation and amortisation",
               "Operating profit: the cash-like profit the business earns before financing costs.",
               "Net profit + interest + depreciation (identified by ledger name)."),
    "hhi": ("HHI", "Herfindahl-Hirschman Index", "How concentrated sales are among customers (0 = spread out, 10,000 = one customer).",
            "Sum of squared % shares of each customer. < 1,500 unconcentrated; 1,500-2,500 moderate; > 2,500 high."),
    "top1": ("Top-1 share", "Largest-customer concentration", "Share of sales from the single largest customer.",
             "Largest customer's LTM sales ÷ total LTM credit-customer sales."),
    "top5": ("Top-5 share", "Top-5 customer concentration", "Share of sales from the five largest customers.",
             "Top 5 customers' LTM sales ÷ total LTM credit-customer sales."),
    "nrr": ("NRR", "Net revenue retention", "How much repeat customers bought this year vs last year.",
            "LTM sales to customers active in both periods ÷ their prior-year sales."),
    "dso": ("DSO", "Days sales outstanding", "Debtor days: average number of days customers take to pay.",
            "Trade receivables ÷ LTM credit sales (incl. GST) × 365."),
    "dpo": ("DPO", "Days payables outstanding", "Creditor days: average number of days the company takes to pay suppliers.",
            "Trade payables ÷ LTM credit purchases (incl. GST) × 365."),
    "dio": ("DIO", "Days inventory outstanding", "Inventory days: how many days of stock the company holds.",
            "Closing stock ÷ LTM COGS × 365."),
    "ccc": ("CCC", "Cash conversion cycle (cash-to-cash cycle)",
            "Days between paying suppliers and collecting from customers: the gap the bank's working-capital limit funds.",
            "DSO + DIO − DPO."),
    "ageing": ("Ageing", "Receivables / payables ageing", "How old the unpaid bills are.",
               "Outstanding split by bill date: bill-wise where Tally tracks bills, else FIFO against invoices."),
    "recv_90": ("Receivables > 90 days", "Overdue ageing bucket", "Share of money owed by customers that is more than 3 months old.",
                "(91-180 + 181-365 + > 365-day buckets) ÷ total receivables."),
    "collection_ratio": ("Collection efficiency", "Collections ÷ billing",
                         "How much of what was billed to customers was actually collected.",
                         "LTM receipts from customers ÷ LTM credit billing."),
    "current_ratio": ("Current ratio", "Current assets ÷ current liabilities",
                      "Can short-term assets pay the bills due within a year? Banks typically look for 1.33× or more.",
                      "(Cash, bank, debtors, stock, advances) ÷ (creditors, taxes, provisions, OD/CC)."),
    "quick_ratio": ("Quick ratio", "Acid-test ratio", "Current ratio without stock: can it pay without selling inventory?",
                    "(Current assets − stock) ÷ current liabilities."),
    "tnw": ("TNW", "Tangible net worth", "The owners' own money in the business, excluding intangible items.",
            "Total assets − outside liabilities − misc. expenses (asset)."),
    "debt_tnw": ("Debt / TNW", "Gearing (debt-to-equity)", "Borrowings for every ₹1 of the owners' own money.",
                 "(Secured + unsecured loans + OD/CC) ÷ TNW."),
    "tol_tnw": ("TOL / TNW", "Total outside liabilities to tangible net worth",
                "Everything owed to outsiders for every ₹1 of the owners' money. Banks commonly cap this around 3-4×.",
                "(Loans + current liabilities) ÷ TNW."),
    "icr": ("ICR", "Interest coverage ratio", "How many times operating profit covers the interest bill.",
            "EBITDA ÷ interest expense."),
    "dscr": ("DSCR", "Debt service coverage ratio (approx.)",
             "How many times operating profit covers interest plus loan instalments. Below 1.2× is usually a concern.",
             "EBITDA ÷ (interest + principal repaid on term and unsecured loans, LTM)."),
    "od_cc": ("OD / CC", "Overdraft / cash credit", "The working-capital limit drawn from the bank.",
              "Credit balances in Bank OD / OCC ledgers and overdrawn current accounts."),
    "cash_receipts": ("Cash receipts share", "Cash share of customer collections",
                      "Share of customer payments received in cash instead of through the bank.",
                      "LTM cash receipts from debtors ÷ all receipts from debtors."),
    "cv": ("CV", "Coefficient of variation (seasonality)", "How much monthly sales swing up and down.",
           "Standard deviation of monthly LTM sales ÷ their mean."),
    "window_dressing": ("Window dressing", "Year-end sales inflation", "Sales booked at year end that are reversed afterwards.",
                        "March sales > 1.6× the year's average month; April credit notes > 10% of March sales."),
    "circular": ("Circular trading", "Round-tripping between related parties",
                 "The same party buying and selling with the company, which can inflate turnover.",
                 "Debtor and creditor ledgers matched by GSTIN or normalised name."),
    "backdating": ("Back-dated entries", "Entries out of creation order", "Vouchers keyed in later but dated earlier.",
                   "Vouchers whose MasterID (creation order) is after vouchers dated 30+ days later."),
    "269st": ("s.269ST", "Income Tax Act s.269ST", "Law barring receipt of ₹2 lakh or more in cash in a transaction.", ""),
    "40a3": ("s.40A(3)", "Income Tax Act s.40A(3)", "Cash expenses above ₹10,000 are not tax-deductible.", ""),
}


def term(key: str) -> dict:
    abbr, name, plain, formula = TERMS[key]
    return {"key": key, "abbr": abbr, "name": name, "plain": plain, "formula": formula}


def all_terms() -> list[dict]:
    return sorted((term(k) for k in TERMS), key=lambda t: t["abbr"].lower())


def _t(key: str) -> str:
    _, _, plain, formula = TERMS[key]
    return f"{plain} {formula}".strip()


# Hover text for every dashboard tile and column, by its label. Labels that
# are a glossary term reuse its wording; tests check that no tile lacks one.
HINTS = {
    "Sales, 12 mo": "Sales booked in the last 12 months, after returns.",
    "Sales, 12 months": "What you sold in the last 12 months, after returns.",
    "Revenue growth": _t("yoy"),
    "Monthly average": "Average sales per month over the last 12 months.",
    "Seasonality": "The month with the highest sales, and how much monthly sales swing. " + _t("cv"),
    "Credit notes / returns": "Credit notes (returns, discounts given back) as a share of gross billing. A high or rising share can mean disputes or reversed sales.",
    "Returns": "Goods returned and credit notes as a share of what you billed.",
    "Cash sales": "Share of sales paid in cash at the time of sale rather than billed on credit.",
    "Customers billed": "How many different customers were billed in the last 12 months.",
    "Gross margin": _t("gross_margin") + " Marked approximate when closing stock could not be read.",
    "EBITDA": _t("ebitda"),
    "EBITDA margin": "EBITDA as a share of sales: operating profit before interest, tax and depreciation for each ₹100 of sales.",
    "Net margin": _t("net_margin"),
    "Profit, 12 months": "Profit after all expenses booked in the last 12 months, before tax.",
    "Interest cost": "Interest booked on loans, overdraft and cash credit in the last 12 months.",
    "Depreciation": "Depreciation booked in the last 12 months: the yearly wear-down of machines, vehicles and other assets.",
    "Overheads": "Indirect expenses (salaries, rent, power, office) as a share of sales.",
    "Other income": "Income outside the main business, such as interest received, discounts or commission.",
    "Cost of goods": _t("cogs"),
    "Receivables": "Money customers owe the company today.",
    "To collect": "Money your customers owe you today.",
    "Debtor days": _t("dso"),
    "Owed > 90 days": "Share of unpaid bills that are more than 3 months old. The amount is shown below.",
    "Collection ratio": _t("collection_ratio"),
    "Top customer": _t("top1"),
    "Top 5 customers": _t("top5"),
    "Customers owing": "How many customers have an unpaid balance today.",
    "Stuck debtors": "Customers who owe money but have paid nothing in the last 90 days.",
    "Payables": "Money the company owes its suppliers today.",
    "You owe suppliers": "Money you owe your suppliers today.",
    "Creditor days": _t("dpo"),
    "Purchases, 12 mo": "Purchases booked in the last 12 months.",
    "Top supplier": "Share of purchases from the single largest supplier.",
    "Top 5 suppliers": "Share of purchases from the five largest suppliers.",
    "Cash cycle": _t("ccc"),
    "Cash tied up": "How many days your money is stuck between paying suppliers and collecting from customers. Shorter is better.",
    "Inventory days": _t("dio"),
    "Stock": "Value of goods in stock on the report date, as Tally values them.",
    "Current ratio": _t("current_ratio"),
    "Net working capital": "Current assets minus current liabilities: the short-term money left over after paying short-term dues.",
    "Current assets": "Cash, bank, money customers owe, stock and advances: what turns into cash within a year.",
    "Current liabilities": "Suppliers, taxes, provisions and the overdraft or cash credit: what must be paid within a year.",
    "Debt / net worth": _t("debt_tnw"),
    "Total liabilities / net worth": _t("tol_tnw"),
    "Interest cover": _t("icr"),
    "DSCR": _t("dscr"),
    "Debt service, 12 mo": "Loan repayments plus interest paid in the last 12 months.",
    "Net worth": _t("tnw"),
    "Loans": "Total borrowings outstanding: term loans, overdraft or cash credit, and unsecured loans.",
    "Bank balance": "Combined balance of all bank accounts on the report date. An overdraft or cash credit counts as negative.",
    "In the bank": "What you have in your bank accounts today, after any overdraft.",
    "Average balance": "Average month-end bank balance over the last 12 months.",
    "Lowest balance": "The lowest month-end bank balance in the last 12 months, and the month it happened.",
    "Balance swings": "How much the month-end bank balance moves up and down. Large swings mean cash comes in lumps.",
    "Cash receipts": _t("cash_receipts"),
    "Large cash receipts": "Cash received of ₹2 lakh or more in one go. " + _t("269st"),
    "Large cash payments": "Cash payments above ₹10,000 in one go. " + _t("40a3"),
    "Days cash went negative": "Days when the cash-in-hand ledger fell below zero, which can't happen with real cash and usually means entries are missing or wrong.",
    "GST collected, 12 mo": "GST charged on sales in the last 12 months.",
    "GST paid, 12 mo": "GST actually paid to the government in the last 12 months.",
    "GST payable now": "GST collected but not yet paid, on the report date.",
    "TDS payable now": "Tax deducted at source that has not yet been paid to the government.",
    "GST vs sales": "Whether GST charged each month moves in line with sales. A mismatch can mean sales booked without tax or tax booked without sales.",
    "GST filing status": "Whether GST returns are filed on time. This needs a link to the GST portal; Tally doesn't hold it.",
    "Books lag": "Days between the report date and the last entry in Tally. A long lag means the books are behind.",
    "Vouchers in books": "Number of entries (sales, purchases, receipts, payments, journals) read from Tally.",
    "Tally company": "The Tally company these books were read from.",
    "Due in 30 days": "Payments due in the next 30 days, such as GST, TDS and loan EMIs. See the to-do list.",
    "Kept customers": _t("nrr"),
    "New customers": "Customers billed this year who were not billed the year before.",
    "Lost customers": "Customers billed last year who have not been billed this year.",
    "To collect from customers": "Money your customers owe you today.",
    "GST payable": "GST you have collected but not yet paid to the government.",
    # Portfolio columns
    "Health": "Attention: any red indicator, a serious red flag, or data overdue. Watch: 3 or more amber indicators, or a new alert. Healthy: everything else.",
    "New alerts": "Changes found since the previous day's data, such as a new red flag or an indicator turning red.",
}


def hint(label: str) -> str:
    return HINTS.get(label, "")
